name = "dimension"
license = "MIT"
licenselink = "https://github.com/panr/hugo-theme-dimension/blob/master/LICENSE.md"
description = "A port of HTML5UP's dimension theme, optimized for markdown based CMS."
homepage = "https://github.com/your-identity/hugo-theme-dimension/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "personal", "responsive", "simple", "responsive"]
features = ["blog", "syntax highlighting"]
min_version = 0.57

[author]
  name = "d-asnaghi"
  homepage = "https://d-asnaghi.github.io"

[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"
